### ISSUE TITLE
How to properly use acquire_packet_id together with C++ 20 coroutines?

### ISSUE THREAD

**Issue by pblxptr** [redboltz/async_mqtt#73]
It's not an issue per se, it's rather a question because I kinda don't fully understand how to properly use the acquire_packet_id method. It's probably due to my misunderstanding of how to use it.

Recently I've stumbled upon the error: 
`td::optional<typename async_mqtt::packet_id_type<PacketIdBytes>::type> async_mqtt::basic_endpoint<Role, PacketIdBytes, NextLayer>::acquire_unique_packet_id() [with async_mqtt::role Role = async_mqtt::role::client; long unsigned int PacketIdBytes = 2; NextLayer = boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::io_context::basic_executor_type<std::allocator<void>, 0> >; typename async_mqtt::packet_id_type<PacketIdBytes>::type = short unsigned int]: Assertion `strand().running_in_this_thread()' failed.`

It took me to take a close look at the documentation and the code of the library. 
There is a part saying that: "f you call those APIs out of strand, then assertion failed.". This statement is followed by a table where one of the entries is: "acquire_unique_packet_id".

Now, let me briefly show (using pseudocode) how I use your client in my code, the code is simple and short so it should be quite easy to understand.

// ClientWrapper - is a wrapper that is using async_mqtt::endpoint<async_mqtt::role::client, async_mqtt::protocol::mqtt>; under the hood

// rethrow - is a function that just rethrows an exception

```
class ClientWrapper
{
boost::asio::awaitable<void> async_send(....)
{
    auto packet_id = ep_.acquire_packet_id();
    [...]
}

boost::asio::awaitable<...> async_receive()
{
  [...]
}

private:
async_mqtt::endpoint<async_mqtt::role::client, async_mqtt::protocol::mqtt> ep_;
};


auto ioc = io_context{};
auto client1 =  ClientWrapper{...};
auto client2 = ClientWrapper{...};

boost::asio::co_spawn(ioc, [&client1, &client2]() -> boost::asio::awaitable<void>()
{
  co_await client1.async_send(...);
  co_await client2.async_send(...);
  
  co_await client1.async_receive(...);
}, rethrow);

```

Notice that I'm using SYNC version of acquire_packet_id. 
So, the error I showed before, and the documentation that says that there is an async version acquire_packet_id took me to the other solution where I replaced SYNC call to acquire_packet_id with async version with boost::use_awaitable completition hander.

So my questions are:
  - should I always use the async version of acquire_packet_id in case of using coroutines?
  - is my fix correct?
  - when should I use SYNC version of acquire_packet_id?
  - why is the return value of async call to acquire_packet_id optional? When can it be returned as nullopt?

**Comment by redboltz** [comment]
Good question.

## should I always use the async version of acquire_packet_id in case of using coroutines?

I recommend always using async version of acquire_packet_id.
It is always safe.

## is my fix correct?

Yes.

## when should I use SYNC version of acquire_packet_id?

You don't need to use SYNC version. But you could call SYNC version in the same endpoint's strand.
For example, 
In the CompletionToken handlng code of the same endpoint. 
Receiving CONNACK then send PUBLISH to the same endpoint.
Receiving PUBLISH then send PUBLISH to the same endpoint (echo back).
See 
https://github.com/redboltz/async_mqtt/blob/d876fc1c0bd1fd4f7f4d7744241d14efa05c31b2/example/ep_cpp20coro_mqtt_client.cpp#L61-L97
The line 83 is runnning in the strand of the same endpoint as CONNACK is received, and sending SUBSCRIBE packet with SYNC acquired_unique_packet_id().

You cannot call ASYNC version out of the strand.
For example, receive PUBLISH packet from endpoint ep1, then send (forward) the PUBLISH packet to ep2. In this case, you shouldn't call SYNC version of acquire_unique_packet_id() of ep2 because the code is runnning on **ep1's strand**.

If you use C++20 coroutine, you wouldn't have much motivation to use SYNC version because C++ coroutine doesn't introduce annoying nested indents.
If you use callback functions instead of `use_awaitable`, then ASYNC version introduces one callback nest. SYNC version can avoid that kind of nest in the allowed case I mentioned above.

## If I call ASYNC version in the same strand, is there any performance penalty compare to SYNC version? (I added the question)

You can ignore the penalty.
Here is ASYNC version implementation:

https://github.com/redboltz/async_mqtt/blob/d876fc1c0bd1fd4f7f4d7744241d14efa05c31b2/include/async_mqtt/endpoint.hpp#L248-L266

https://github.com/redboltz/async_mqtt/blob/d876fc1c0bd1fd4f7f4d7744241d14efa05c31b2/include/async_mqtt/endpoint.hpp#L755-L778

Simply calling `boost::asio::dispatch` to run on the strand, and then call `ep.pid_man_.acquire_unique_id()`.

Here is `boost::asio::dispatch` document:
https://www.boost.org/doc/html/boost_asio/reference/dispatch/overload2.html

If `boost::asio::dispatch` is called from the same strand of the first parameter, then calling the second parameter in the dispatch funtion immediately.
The function call is usually inlined when you enable optimization like `-O2`.
So the cost is only checking the Executor ex is running on the strand or not. It is very small.

## why is the return value of async call to acquire_packet_id optional? When can it be returned as nullopt?

MQTT spec allowed 1-65535(0xffff) packet_ids. If you use all of them and then calling acuire_unique_packet_id(), then it returns nullopt.
async_mqtt allocated unique packet_id efficiently. I implement it the previous project mqtt_cpp and port it to async_mqtt and number-allocator for JS https://www.npmjs.com/package/number-allocator . JS version is used by MQTT.js.
JS version has the better document so you can refer it to understand the performance and algorithm.

The important point is packet_id is managed by endpoint. It doesn't generated simple increment algorithm. It can avoid conflict. It is very important.

When you acquire or register packet_id, then the packet_id becomes `using` status. Then you pass to the packet_id to the some packet, and call `send()`. At that time, the management responsibility of the packet_id is moved to the endpoint.
The packet_id would reusable when the following events happned on the endpoint.

1. PUBACK is received when the packet_id is used for sending PUBLISH QoS1.
2. PUBREC with error reason_code is received when the packet_id is used for sending PUBLISH QoS2.
3. PUBCOMP is received when the packet_id is used for sending PUBLISH QoS2.
4. SUBACK is received when the packet_id is used for sending SUBSCRIBE.
5. UNSUBACK is received when the packet_id is used for sending UNSUBSCRIBE.
6. MQTT session is cleared. (e.g. recieve CONNACK with session_present false)

**Comment by pblxptr** [comment]
@redboltz Thank you very much for the in-depth explanation!

**Comment by redboltz** [comment]
You are welcome!

**Comment by redboltz** [comment]
Recently, the strand treatment is updated.
See https://github.com/redboltz/async_mqtt/blob/main/test/unit/ut_cpp20coro_exec.cpp

It is the same behavior as Boost.Asio APIs. So async_mqtt respect it.
I recommend that `BOOST_AUTO_TEST_CASE(same)` approach.
