### ISSUE TITLE
Knowing if the connection is open

### ISSUE THREAD

**Issue by magni-mar** [redboltz/async_mqtt#83]
I have been dealing with this problem for a while now and hoping that you could help me.

What is the best way to know it the connection has died or has been lost? I cannot find the API to get this information.

**Comment by redboltz** [comment]
You can know MQTT level status as follows:

First, call recv(), then you can get packet_variant as the CompletionToken of the recv().
https://github.com/redboltz/async_mqtt/blob/9a9160c2dd0309e3be1543ccd9101aec9611da3a/include/async_mqtt/packet/packet_variant.hpp#L184-L215
The index 0 of the packet_variant is system_error.
If connection is lost, then the system_error is set. 

For convinience, packet_variant has operator bool().
https://github.com/redboltz/async_mqtt/blob/9a9160c2dd0309e3be1543ccd9101aec9611da3a/include/async_mqtt/packet/packet_variant.hpp#L179-L181

If you want to know the reason of connection lost, you can get system_error from the packet_variant, then call `.what()` function.

**Comment by magni-mar** [comment]
My problem is that I want to check weather the connection is open while I am actively receiving in another place in the program. This causes me to not be able to initiate another receive.

**Comment by redboltz** [comment]
You can store the result of recv() in your application as a flag.

I guess that you would expect something like `bool endpoint::connected()`. But there is no such function because it is not a good idea.

async_mqtt doesn't own io_context. Just refer it.
So how to call io_context::run() is client's responsibility. It could call from different thread or multiple threads.

In this case the return valur of `connected()` is unreliable.

```cpp
if (ep.connected()) {
    // could have already been disconnected here
}
```

When the status flag is reliable ? Only application developper knows it.
So it should be implemented by application side, not in the library.

**Comment by magni-mar** [comment]
I understand, thanks for the response.
